### ISSUE TITLE
Trouble with multilanguage setup

### ISSUE THREAD

**Issue by SmittyW3rben** [brainworxx/form_newsletter#1]
I am using the extension with Typo3 version 10.4.9. The extension version is current (1.4.0). The default language is English so everything worked perfectly there. Then I created a German-language page and copied the content (all settings of the extension remained the same). As soon as I use the German registration form, I am not redirected to an error page or a success page, the page reloads and that's it. There is also no registration with newsletter2go. I don't get an error message in the logs. Is this a known problem?

**Comment by jmeinert** [comment]
Unfortunately I cannot recreate your problem. The finisher works fine on a translated page both in connected and free mode.
If nothing happened and no error was thrown, the finisher probably wasn't triggered in the first place.
Make sure the TypoScript static file is included on your page. Also make sure the redirect finisher is not used within your registration form as it stops any finisher coming after it. Check the [documentation ](https://docs.typo3.org/p/brainworxx/form-newsletter/master/en-us/Config/Index.html) for more information.

**Comment by jmeinert** [comment]
Closing this issue for now as the problem likely is a result of a faulty configuration.
