### ISSUE TITLE
Abandoned or plans to support TYPO3 13?

### ISSUE THREAD

**Issue by julescakecrumb** [brainworxx/form_newsletter#2]
Hi,

are there any plans to update the extension for TYPO3 13? 
And to adjust it for brevo if neccessary (because Newsletter2Go became Sendinblue and is now brevo)?

Or is this package abandoned (last changes were in 2020).

Thank you and kind regards!

**Comment by jmeinert** [comment]
Hi there,

Thank you for checking out this little extension!

Right now, there are no plans to provide support for TYPO3 13.
There is already an extension by Georg Ringer you can use for an integration of Brevo in TYPO3 with the form extension: https://github.com/studiomitte/brevo.

On that note, I should archive this repo.
